### ISSUE TITLE
[BUG] Null function pointer when cancelling nonlinked removal

### ISSUE THREAD

**Issue by SirAxolot** [FoxelTheFennic/Paint-3D-Project-Manager#3]
**Describe the bug**
The program crashes when you hit no in the removing nonlinked folders dialogue

**To Reproduce**
1. Press R Key
2. Hit No
3. lol
![image](https://user-images.githubusercontent.com/89815386/229943501-63d072b9-980b-473a-86c6-4517645e2b73.png)

**Expected behavior**
Closing the window

**Comment by FoxelTheFennic** [comment]
how the hell did i miss this LMAO, ill fix it rq

**Comment by FoxelTheFennic** [comment]
fixed in newest commit
